<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Subscribe/Unsubscribe — WebNode</title>
    <link rel="stylesheet" href="app/layouts/style.css">
  </head>

  <body class="absolute full-width full-height no-margin">
    <form class="flexbox-container flexbox-vertical full-width">
      <h1><label for="group-select"><u>N</u>ewsgroups</label></h1>
      <div class="flexbox-fill flexbox-container flexbox-horizontal">
        <select name="group" id="group-select" class="flexbox-fill" size="30" multiple>
        <?php foreach ($this->groups as $group): ?>
          <option value="<?= $group['name'] ?>"><?= $group['name'] ?></option>
        <?php endforeach; ?>
        </select>
        <div class="flexbox-container flexbox-vertical">
          <input type="button" value=">>"><br>
          <input type="button" value="<<">
        </div>
        <select name="group" id="group-select" class="flexbox-fill" size="30" multiple>
        <?php // foreach ($this->subscribedGroups as $group): ?>
          <!-- <option value="<?= $group['name'] ?>"><?= $group['name'] ?></option> -->
        <?php // endforeach; ?>
        </select>
      </div>
    </form>
  </body>
</html>
