<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Newsgroups — WebNode</title>
    <link rel="stylesheet" href="app/layouts/style.css">
    <script type="text/javascript">
      function openGroupList ()
      {
        var w = window.open("?controller=groups", "wGroups", "width=800,height=600");
        if (w) w.focus();
      }
    </script>
  </head>

  <body class="absolute full-width full-height no-margin">
    <form class="flexbox-container flexbox-vertical full-height">
      <h1 class="hidden"><label for="group-select"><u>N</u>ewsgroup:</label></h1>
      <div class="flexbox-container flexbox-horizontal">
        <input type="button" class="flexbox-fill" value="Subscribe…" onclick="openGroupList()">
        <input type="button" class="flexbox-fill" value="Unsubscribe…">
      </div>
      <select name="group" id="group-select" class="flexbox-fill" size="7" multiple>
        <optgroup label="news.solani.org">
          <option value="news.solani.org/comp.lang.javascript">comp.lang.javascript</option>
        </optgroup>
        <optgroup label="news6.open-news-network.org">
          <option value="news6.open-news-network.org/sci.physics.relativity">sci.physics.relativity</option>
        </optgroup>
      </select>
    </form>
  </body>
</html>
