<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Newsgroups — WebNode</title>
    <style>
      .absolute { position: absolute; }
      .no-margin { margin: 0; }
      .absolute.full-width { left: 0; right: 0; }
      .absolute.full-height { top: 0;bottom: 0; }
      .full-height { height: 100%; }
      .full-width { width: 100%; }
    </style>
  </head>

  <body>
    <form class="absolute full-width full-height">
      <h1><label for="group-select"><u>N</u>ewsgroup:</label></h1>
      <select name="group" id="group-select" class="full-width" size="30">
      <?php foreach ($this->groups as $group): ?>
        <option value="<?= $group['name'] ?>"><?= $group['name'] ?></option>
      <?php endforeach; ?>
      </select>
      <input type="button" value="Subscribe…">
      <input type="button" value="Unsubscribe…">
    </form>
  </body>
</html>
