<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN"
  "http://www.w3.org/TR/html4/frameset.dtd">
<html>
  <head>
    <title>WebNode</title>
    <style>
      body {
        margin: 0;
        font-family: sans-serif;
      }
    </style>
  </head>
  <frameset cols="33%,*">
    <frame name="groups" src="?action=groups">
    <frameset rows="50%,*">
      <frame name="threads" src="?action=threads">
      <frame name="posting" src="?action=posting">
    </frameset>
  </frameset>
</html>
