<!DOCTYPE html>
<html>
  <head>
    <title>WebNode</title>
    <style>
      body {
        margin: 0;
        font-family: sans-serif;
      }
    </style>
  </head>
  <frameset cols="33%,*">
    <frame name="groups" src="groups.phtml">
    <frameset rows="50%,*">
      <frame name="threads" src="threads.phtml">
      <frame name="posting" src="posting.phtml">
    </frameset>
  </frameset>
</html>
